version: "3"

services:
  dynamodb:
    image: "amazon/dynamodb-local"
    command: "-jar DynamoDBLocal.jar -dbPath /data -sharedDb"
    ports:
      - "8000:8000"
    volumes:
      - "/avalon/DynamoDB/data:/data"

  vault:
    image: "vault"
    ports:
      - "8200:8200"
    volumes:
      - "/Vault/logs:/logs"
    environment:
      VAULT_DEV_TOKEN: "dev"
