apiVersion: skaffold/v1beta4
kind: Config
build:
  artifacts:
    - image: gcr.io/k8s-skaffold/avalon-server
      context: ./Avalon.Server/
deploy:
  kubectl:
    manifests:
      - Avalon.Server/k8s/*
