settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: Avalon.Server
    path: .
    commands: {}
    watcher:
      extensions:
        - go
      paths:
        - /
      ignore:
        paths:
          - .git
          - .realize
          - vendor
