apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalon-client
  labels:
    app: avalon-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avalon-client
  template:
    metadata:
      labels:
        app: avalon-client
    spec:
      containers:
        - name: avalon-client
          image: gcr.io/k8s-skaffold/avalon-client
          ports:
            - containerPort: 3000
