apiVersion: v1
kind: Service
metadata:
  name: avalon-client
  labels:
    app: avalon-client
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: avalon-client
