import {
  attribute,
  autoGeneratedHashKey,
  rangeKey,
  hashKey,
  table
} from "@aws/dynamodb-data-mapper-annotations";
import { embed } from "@aws/dynamodb-data-mapper";
import { Player } from "./player";
import { Mission } from "./mission";

export class Setup {
  @attribute()
  morgana: boolean;

  @attribute()
  merlin: boolean;

  @attribute()
  mordred: boolean;

  @attribute()
  oberon: boolean;

  @attribute()
  percival: boolean;
}

@table(process.env.DYNAMODB_TABLE)
export class Lobby {
  @autoGeneratedHashKey()
  id: string;

  @rangeKey({ defaultProvider: () => new Date() })
  createdAt: Date;

  @hashKey()
  code: string;

  @attribute({ memberType: embed(Player) })
  players: Array<Player>;

  @attribute()
  connectionId: Array<string>;

  @attribute({ memberType: embed(Mission) })
  rounds: Array<Mission>;

  @attribute()
  event: Array<Event>;
}
