import {
  attribute,
  autoGeneratedHashKey,
  table
} from "@aws/dynamodb-data-mapper-annotations";
import { embed } from "@aws/dynamodb-data-mapper";
import { Player, Setup, Game, Event } from "./";

import moment = require("moment");
import * as uuid from "uuid/v1";

@table(process.env.DYNAMODB_TABLE)
export class Lobby {
  @autoGeneratedHashKey()
  id: string;

  @attribute()
  createdAt: Date;

  @attribute()
  code: string;

  @attribute({ memberType: embed(Player) })
  players: Array<Player>;

  @attribute({ memberType: embed(Setup) })
  setup: Setup;

  @attribute({ memberType: embed(Game) })
  game: Game;

  @attribute({ memberType: embed(Event) })
  events: Array<Event>;

  constructor() {
    this.code = uuid()
      .substring(0, 4)
      .toUpperCase();
    this.createdAt = moment(moment.now()).toDate();
    this.game = new Game();
    this.players = [];
    this.setup = new Setup();
    this.events = [];
  }

  getNumberOfPlayers() {
    return this.players.length;
  }

  getConnections() {
    return this.players.map(player => player.connectionId);
  }
}
