import {
  attribute,
  autoGeneratedHashKey,
  rangeKey,
  hashKey,
  table,
  versionAttribute
} from "@aws/dynamodb-data-mapper-annotations";

export class Vote {
  @attribute()
  player: string;

  @attribute()
  token: boolean;
}

export class Mission {
  @attribute()
  success: boolean;

  @attribute()
  votes: Array<Vote>;
}
