import {
  attribute,
  autoGeneratedHashKey,
  rangeKey,
  hashKey,
  table,
  versionAttribute
} from "@aws/dynamodb-data-mapper-annotations";
// import uuidV4 = require("uuid/v4");

export class Player {
  @attribute()
  connectionId: string;

  @attribute()
  name: string;

  @attribute()
  role: number;

  @attribute()
  number: number;
}
