apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dynamodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
        - name: dynamodb
          image: amazon/dynamodb-local
          env:
            - name: PORT
              value: "8081"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8000
