apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dynamodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
        - name: dynamodb
          image: amazon/dynamodb-local
          # args: ["-jar", "DynamoDBLocal.jar", "-dbPath", /dynamodb_local_db"]
          env:
            - name: PORT
              value: "8000"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: dynamodb
              mountPath: /dynamodb_local_db
      volumes:
        - name: dynamodb
          hostPath:
            path: /data
            type: DirectoryOrCreate
