service: avalon-serverless # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"
    - Effect: Allow
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:BatchGetItem"
        - "dynamodb:BatchWriteItem"
        - "dynamodb:Query"
      Resource:
        - Fn::GetAtt: [lobbyTable, Arn]
        - Fn::Join:
            - "/"
            - - Fn::GetAtt: [lobbyTable, Arn]
              - "*"
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource:
        - ${self:custom.myTopic}

websocketApiRouteSelectionExpression: $request.body.action

functions:
  connectionLobby:
    handler: src/lib/lobby.connectionLobby
    events:
      - http:
          path: connection
          method: get
  lobbyCreateCommand:
    handler: src/lib/lobby-lambda.lobbyHandler
    events:
      - http:
          path: lobby
          method: post
  lobbyStartCommand:
    handler: src/lib/game-lambda.gameHandler
    events:
      - http:
          path: game
          method: post
  voteCommand:
    handler: src/lib/vote-lambda.voteHandler
    events:
      - http:
          path: vote
          method: post
  voteNotification:
    handler: src/lib/notification/vote-notification.voteNotification
    events:
      - sns:
          topicName: dispatch
          filterPolicy:
            type:
              - vote

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: code
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: code
            Projection:
              ProjectionType: ALL
            KeySchema:
              - AttributeName: code
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5

custom:
  myTopic:
    Fn::Join:
      - ":"
      - - arn
        - aws
        - sns
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - dispatch
  webpack:
    includeModules: true
    packager: "npm"
    package:
      individually: true
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true

plugins:
  - serverless-websockets-plugin
  - serverless-dynamodb-local
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-step-functions
  - serverless-offline-sqs
  - serverless-offline-sns
  - serverless-offline
